name: Trigger auto deployment for testaiownik

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/testaiownik-AutoDeployTrigger-5619ea43-f9b5-4624-811d-11305dd19990.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTAIOWNIK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTAIOWNIK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTAIOWNIK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}src/Testaiownik/Backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: testaiownik.azurecr.io
          registryUsername: ${{ secrets.TESTAIOWNIK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTAIOWNIK_REGISTRY_PASSWORD }}
          containerAppName: testaiownik
          resourceGroup: ACRTestaiownik
          imageToBuild: testaiownik.azurecr.io/testaiownik:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


